name: notify
description: A new Flutter project.
publish_to: 'meg4cyberc4t'


version: 1.0.0+1
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  supercharged: ^2.1.1
  simple_animations: ^4.0.1
  flutter_native_splash: ^1.3.1
  flutter_bloc: ^8.0.0
  flutter_material_color_picker: ^1.1.0+2
  bottom_nav_layout: ^3.0.9
  google_nav_bar: ^5.0.5
  flutter_sticky_header: ^0.6.0
  intl: ^0.17.0
  auto_animated: ^3.0.1
  
  firebase: ^9.0.2
  firebase_auth: ^3.3.0
  firebase_core: ^1.10.2
  provider: ^6.0.1
  cloud_firestore: ^3.1.1
  qr_flutter: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  

flutter_native_splash:
  background_image: "assets/splashscreen.png"
  android: true
  ios: true
  # flutter pub run flutter_native_splash:create




  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #


