name: notify
description: An application for creating and working reminders in a team.
# publish_to: 'meg4cyberc4t'

version: 1.0.0+1
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2 # For icons
  google_fonts: ^2.1.0 # For fonts
  flutter_native_splash: ^1.3.1 # For splash screen
  flutter_material_color_picker: ^1.1.0+2 # For color picker
  flutter_sticky_header: ^0.6.0 # For special header in homepage
  firebase_auth: ^3.3.0 # For authentication
  cloud_firestore: ^3.1.1 # For work with database
  provider: ^6.0.1 # For get data from the context
  bottom_sheet: ^1.0.5 # For bottom sheet
  stream_transform: ^2.0.0 # For merging streams (FirebaseService)
  flutter_redux: ^0.8.2 # For update screen state
  flutter_local_notifications: ^9.2.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  timezone: ^0.8.0
  firebase_core: ^1.10.6
  redux: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/
    - google_fonts/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  
flutter_native_splash:
  background_image: "assets/splashscreen.png"
  android: true
  ios: true
  # flutter pub run flutter_native_splash:create