name: notify
description: An application for creating and working reminders in a team.
version: 0.2.1+5
repository: https://github.com/meg4cyberc4t/notify

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.4.0
  flutter_localizations:
    sdk: flutter
  flutter_material_color_picker: ^1.1.0+2
  flutter_native_timezone: ^2.0.0
  flutter_vibrate: ^1.3.0
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  package_info_plus: ^1.4.0
  provider: ^6.0.2
  rive: ^0.8.4
  rive_splash_screen: ^0.1.0
  shared_preferences: ^2.0.12
  shimmer: ^2.0.0
  timezone: ^0.8.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.7
  json_serializable: ^6.1.4


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/fonts/static/
    - assets/rive/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png" # flutter pub run flutter_launcher_icons:main

  # For generating key:
  # keytool -genkey -v -keystore ~/.keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias key -storetype JKS
  # gradlew signingReport 

  # For generating json models:
  # flutter pub run build_runner build