name: notify
description: A new Flutter project.
# publish_to: 'meg4cyberc4t'
publish_to: 'none'


version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  supercharged: ^2.1.1
  simple_animations: ^4.0.1
  flutter_native_splash: ^1.3.1
  megasdkdart:
    git: 
      url: https://github.com/meg4cyberc4t/megasdkdart
      ref: main
  flutter_bloc: ^8.0.0
  hive_flutter: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  

flutter_native_splash:
  background_image: "assets/splashscreen.png"
  android: true
  ios: true



  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #


