name: notify
description: An application for creating and working reminders in a team.
version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_material_color_picker: ^1.1.0+2
  google_fonts: ^2.2.0
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png" # flutter pub run flutter_launcher_icons:main