name: Dart

on:
  push:
    branches:
    - stable
    - beta
  pull_request:
    branches: 
    - stable
    - beta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

        run: flutter pub upgrade

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze
        
      - name: Run tests
        run: flutter test
